AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  go-al2

  Sample SAM Template for go-al2
Globals:
  Function:
    Timeout: 5

Resources:
  HelloWorldFunction: # Makefile 内でここの名前を指定する必要がある
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: bootstrap
      Runtime: provided.al2 # Amazon Linux 2 ベース
      Architectures: [arm64] # arm64（Graviton2) 指定
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
    Metadata:
      BuildMethod: makefile # go build の設定ファイル

Outputs:
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
